version: "2"
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    ports:
       - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=your_root_password
    volumes:
       - /var/lib/mysql:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: phpmyadmin
    ports:
       - "80:80"
    environment:   
       - PMA_HOST=mysql
    restart: always
