version: "2"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
       - "5432:5432"
    environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=your_root_password
    volumes:
       - /var/lib/postgres:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    ports:
       - "80:80"
    environment:   
       - PGADMIN_DEFAULT_EMAIL=user@domain.com
       - PGADMIN_DEFAULT_PASSWORD=your_root_password
    restart: always
